// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzRx7eW_5OyGbrkIp_x67AKcl6r5bE_vY',
    appId: '1:791734977318:web:b7d3aed7daeb67a19077e7',
    messagingSenderId: '791734977318',
    projectId: 'reina-0414',
    authDomain: 'reina-0414.firebaseapp.com',
    storageBucket: 'reina-0414.firebasestorage.app',
    measurementId: 'G-W06046B16N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-brlh1PvxcB_1tfy-LJFISTmzkhzy1vA',
    appId: '1:791734977318:android:67ff33a347dbc1709077e7',
    messagingSenderId: '791734977318',
    projectId: 'reina-0414',
    storageBucket: 'reina-0414.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ0FxgYKt9Lhz-e1eYHkOhgiOJ1qNw7ak',
    appId: '1:791734977318:ios:c984b5d81ef342b89077e7',
    messagingSenderId: '791734977318',
    projectId: 'reina-0414',
    storageBucket: 'reina-0414.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ0FxgYKt9Lhz-e1eYHkOhgiOJ1qNw7ak',
    appId: '1:791734977318:ios:c984b5d81ef342b89077e7',
    messagingSenderId: '791734977318',
    projectId: 'reina-0414',
    storageBucket: 'reina-0414.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzRx7eW_5OyGbrkIp_x67AKcl6r5bE_vY',
    appId: '1:791734977318:web:5a8cc6e59ac563a89077e7',
    messagingSenderId: '791734977318',
    projectId: 'reina-0414',
    authDomain: 'reina-0414.firebaseapp.com',
    storageBucket: 'reina-0414.firebasestorage.app',
    measurementId: 'G-5BFQTXLN5H',
  );
}
